package com.zhuanjingkj.stpbe.platform.domain;

public class CameraType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera_type.camera_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Integer cameraTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera_type.camera_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private String cameraTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera_type.camera_type_id
     *
     * @return the value of t_camera_type.camera_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Integer getCameraTypeId() {
        return cameraTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera_type.camera_type_id
     *
     * @param cameraTypeId the value for t_camera_type.camera_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setCameraTypeId(Integer cameraTypeId) {
        this.cameraTypeId = cameraTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera_type.camera_type_name
     *
     * @return the value of t_camera_type.camera_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getCameraTypeName() {
        return cameraTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera_type.camera_type_name
     *
     * @param cameraTypeName the value for t_camera_type.camera_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setCameraTypeName(String cameraTypeName) {
        this.cameraTypeName = cameraTypeName == null ? null : cameraTypeName.trim();
    }
}