package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CameraExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public CameraExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCameraIdIsNull() {
            addCriterion("camera_id is null");
            return (Criteria) this;
        }

        public Criteria andCameraIdIsNotNull() {
            addCriterion("camera_id is not null");
            return (Criteria) this;
        }

        public Criteria andCameraIdEqualTo(Long value) {
            addCriterion("camera_id =", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotEqualTo(Long value) {
            addCriterion("camera_id <>", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdGreaterThan(Long value) {
            addCriterion("camera_id >", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdGreaterThanOrEqualTo(Long value) {
            addCriterion("camera_id >=", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdLessThan(Long value) {
            addCriterion("camera_id <", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdLessThanOrEqualTo(Long value) {
            addCriterion("camera_id <=", value, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdIn(List<Long> values) {
            addCriterion("camera_id in", values, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotIn(List<Long> values) {
            addCriterion("camera_id not in", values, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdBetween(Long value1, Long value2) {
            addCriterion("camera_id between", value1, value2, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraIdNotBetween(Long value1, Long value2) {
            addCriterion("camera_id not between", value1, value2, "cameraId");
            return (Criteria) this;
        }

        public Criteria andCameraCodeIsNull() {
            addCriterion("camera_code is null");
            return (Criteria) this;
        }

        public Criteria andCameraCodeIsNotNull() {
            addCriterion("camera_code is not null");
            return (Criteria) this;
        }

        public Criteria andCameraCodeEqualTo(String value) {
            addCriterion("camera_code =", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeNotEqualTo(String value) {
            addCriterion("camera_code <>", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeGreaterThan(String value) {
            addCriterion("camera_code >", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeGreaterThanOrEqualTo(String value) {
            addCriterion("camera_code >=", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeLessThan(String value) {
            addCriterion("camera_code <", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeLessThanOrEqualTo(String value) {
            addCriterion("camera_code <=", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeLike(String value) {
            addCriterion("camera_code like", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeNotLike(String value) {
            addCriterion("camera_code not like", value, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeIn(List<String> values) {
            addCriterion("camera_code in", values, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeNotIn(List<String> values) {
            addCriterion("camera_code not in", values, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeBetween(String value1, String value2) {
            addCriterion("camera_code between", value1, value2, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andCameraCodeNotBetween(String value1, String value2) {
            addCriterion("camera_code not between", value1, value2, "cameraCode");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(Long value) {
            addCriterion("site_id =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(Long value) {
            addCriterion("site_id <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(Long value) {
            addCriterion("site_id >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(Long value) {
            addCriterion("site_id >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(Long value) {
            addCriterion("site_id <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(Long value) {
            addCriterion("site_id <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<Long> values) {
            addCriterion("site_id in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<Long> values) {
            addCriterion("site_id not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(Long value1, Long value2) {
            addCriterion("site_id between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(Long value1, Long value2) {
            addCriterion("site_id not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andRecStateIsNull() {
            addCriterion("rec_state is null");
            return (Criteria) this;
        }

        public Criteria andRecStateIsNotNull() {
            addCriterion("rec_state is not null");
            return (Criteria) this;
        }

        public Criteria andRecStateEqualTo(Byte value) {
            addCriterion("rec_state =", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateNotEqualTo(Byte value) {
            addCriterion("rec_state <>", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateGreaterThan(Byte value) {
            addCriterion("rec_state >", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("rec_state >=", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateLessThan(Byte value) {
            addCriterion("rec_state <", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateLessThanOrEqualTo(Byte value) {
            addCriterion("rec_state <=", value, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateIn(List<Byte> values) {
            addCriterion("rec_state in", values, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateNotIn(List<Byte> values) {
            addCriterion("rec_state not in", values, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateBetween(Byte value1, Byte value2) {
            addCriterion("rec_state between", value1, value2, "recState");
            return (Criteria) this;
        }

        public Criteria andRecStateNotBetween(Byte value1, Byte value2) {
            addCriterion("rec_state not between", value1, value2, "recState");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdIsNull() {
            addCriterion("camera_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdIsNotNull() {
            addCriterion("camera_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdEqualTo(Integer value) {
            addCriterion("camera_type_id =", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdNotEqualTo(Integer value) {
            addCriterion("camera_type_id <>", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdGreaterThan(Integer value) {
            addCriterion("camera_type_id >", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("camera_type_id >=", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdLessThan(Integer value) {
            addCriterion("camera_type_id <", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("camera_type_id <=", value, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdIn(List<Integer> values) {
            addCriterion("camera_type_id in", values, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdNotIn(List<Integer> values) {
            addCriterion("camera_type_id not in", values, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("camera_type_id between", value1, value2, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andCameraTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("camera_type_id not between", value1, value2, "cameraTypeId");
            return (Criteria) this;
        }

        public Criteria andRtspUrlIsNull() {
            addCriterion("rtsp_url is null");
            return (Criteria) this;
        }

        public Criteria andRtspUrlIsNotNull() {
            addCriterion("rtsp_url is not null");
            return (Criteria) this;
        }

        public Criteria andRtspUrlEqualTo(String value) {
            addCriterion("rtsp_url =", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlNotEqualTo(String value) {
            addCriterion("rtsp_url <>", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlGreaterThan(String value) {
            addCriterion("rtsp_url >", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlGreaterThanOrEqualTo(String value) {
            addCriterion("rtsp_url >=", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlLessThan(String value) {
            addCriterion("rtsp_url <", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlLessThanOrEqualTo(String value) {
            addCriterion("rtsp_url <=", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlLike(String value) {
            addCriterion("rtsp_url like", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlNotLike(String value) {
            addCriterion("rtsp_url not like", value, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlIn(List<String> values) {
            addCriterion("rtsp_url in", values, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlNotIn(List<String> values) {
            addCriterion("rtsp_url not in", values, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlBetween(String value1, String value2) {
            addCriterion("rtsp_url between", value1, value2, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtspUrlNotBetween(String value1, String value2) {
            addCriterion("rtsp_url not between", value1, value2, "rtspUrl");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrIsNull() {
            addCriterion("rtp_push_addr is null");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrIsNotNull() {
            addCriterion("rtp_push_addr is not null");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrEqualTo(String value) {
            addCriterion("rtp_push_addr =", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrNotEqualTo(String value) {
            addCriterion("rtp_push_addr <>", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrGreaterThan(String value) {
            addCriterion("rtp_push_addr >", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrGreaterThanOrEqualTo(String value) {
            addCriterion("rtp_push_addr >=", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrLessThan(String value) {
            addCriterion("rtp_push_addr <", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrLessThanOrEqualTo(String value) {
            addCriterion("rtp_push_addr <=", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrLike(String value) {
            addCriterion("rtp_push_addr like", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrNotLike(String value) {
            addCriterion("rtp_push_addr not like", value, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrIn(List<String> values) {
            addCriterion("rtp_push_addr in", values, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrNotIn(List<String> values) {
            addCriterion("rtp_push_addr not in", values, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrBetween(String value1, String value2) {
            addCriterion("rtp_push_addr between", value1, value2, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andRtpPushAddrNotBetween(String value1, String value2) {
            addCriterion("rtp_push_addr not between", value1, value2, "rtpPushAddr");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNull() {
            addCriterion("web_url is null");
            return (Criteria) this;
        }

        public Criteria andWebUrlIsNotNull() {
            addCriterion("web_url is not null");
            return (Criteria) this;
        }

        public Criteria andWebUrlEqualTo(String value) {
            addCriterion("web_url =", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotEqualTo(String value) {
            addCriterion("web_url <>", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThan(String value) {
            addCriterion("web_url >", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlGreaterThanOrEqualTo(String value) {
            addCriterion("web_url >=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThan(String value) {
            addCriterion("web_url <", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLessThanOrEqualTo(String value) {
            addCriterion("web_url <=", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlLike(String value) {
            addCriterion("web_url like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotLike(String value) {
            addCriterion("web_url not like", value, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlIn(List<String> values) {
            addCriterion("web_url in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotIn(List<String> values) {
            addCriterion("web_url not in", values, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlBetween(String value1, String value2) {
            addCriterion("web_url between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andWebUrlNotBetween(String value1, String value2) {
            addCriterion("web_url not between", value1, value2, "webUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlIsNull() {
            addCriterion("ftp_url is null");
            return (Criteria) this;
        }

        public Criteria andFtpUrlIsNotNull() {
            addCriterion("ftp_url is not null");
            return (Criteria) this;
        }

        public Criteria andFtpUrlEqualTo(String value) {
            addCriterion("ftp_url =", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlNotEqualTo(String value) {
            addCriterion("ftp_url <>", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlGreaterThan(String value) {
            addCriterion("ftp_url >", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_url >=", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlLessThan(String value) {
            addCriterion("ftp_url <", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlLessThanOrEqualTo(String value) {
            addCriterion("ftp_url <=", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlLike(String value) {
            addCriterion("ftp_url like", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlNotLike(String value) {
            addCriterion("ftp_url not like", value, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlIn(List<String> values) {
            addCriterion("ftp_url in", values, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlNotIn(List<String> values) {
            addCriterion("ftp_url not in", values, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlBetween(String value1, String value2) {
            addCriterion("ftp_url between", value1, value2, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andFtpUrlNotBetween(String value1, String value2) {
            addCriterion("ftp_url not between", value1, value2, "ftpUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlIsNull() {
            addCriterion("upload_url is null");
            return (Criteria) this;
        }

        public Criteria andUploadUrlIsNotNull() {
            addCriterion("upload_url is not null");
            return (Criteria) this;
        }

        public Criteria andUploadUrlEqualTo(String value) {
            addCriterion("upload_url =", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlNotEqualTo(String value) {
            addCriterion("upload_url <>", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlGreaterThan(String value) {
            addCriterion("upload_url >", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlGreaterThanOrEqualTo(String value) {
            addCriterion("upload_url >=", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlLessThan(String value) {
            addCriterion("upload_url <", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlLessThanOrEqualTo(String value) {
            addCriterion("upload_url <=", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlLike(String value) {
            addCriterion("upload_url like", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlNotLike(String value) {
            addCriterion("upload_url not like", value, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlIn(List<String> values) {
            addCriterion("upload_url in", values, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlNotIn(List<String> values) {
            addCriterion("upload_url not in", values, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlBetween(String value1, String value2) {
            addCriterion("upload_url between", value1, value2, "uploadUrl");
            return (Criteria) this;
        }

        public Criteria andUploadUrlNotBetween(String value1, String value2) {
            addCriterion("upload_url not between", value1, value2, "uploadUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_camera
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}