package com.zhuanjingkj.stpbe.platform.domain;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.image_url
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.image_path
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private String imagePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.upload_time
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.camera_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long cameraId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.user_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.lng
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Double lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.lat
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.vehicle_num
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Integer vehicleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.video_stream_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long videoStreamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.image_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Long imageTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.detail
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.image_id
     *
     * @return the value of t_image.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.image_id
     *
     * @param imageId the value for t_image.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.image_url
     *
     * @return the value of t_image.image_url
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.image_url
     *
     * @param imageUrl the value for t_image.image_url
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.image_path
     *
     * @return the value of t_image.image_path
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.image_path
     *
     * @param imagePath the value for t_image.image_path
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.upload_time
     *
     * @return the value of t_image.upload_time
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.upload_time
     *
     * @param uploadTime the value for t_image.upload_time
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.camera_id
     *
     * @return the value of t_image.camera_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getCameraId() {
        return cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.camera_id
     *
     * @param cameraId the value for t_image.camera_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setCameraId(Long cameraId) {
        this.cameraId = cameraId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.user_id
     *
     * @return the value of t_image.user_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.user_id
     *
     * @param userId the value for t_image.user_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.lng
     *
     * @return the value of t_image.lng
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.lng
     *
     * @param lng the value for t_image.lng
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.lat
     *
     * @return the value of t_image.lat
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.lat
     *
     * @param lat the value for t_image.lat
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setLat(Long lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.vehicle_num
     *
     * @return the value of t_image.vehicle_num
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Integer getVehicleNum() {
        return vehicleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.vehicle_num
     *
     * @param vehicleNum the value for t_image.vehicle_num
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setVehicleNum(Integer vehicleNum) {
        this.vehicleNum = vehicleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.video_stream_id
     *
     * @return the value of t_image.video_stream_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getVideoStreamId() {
        return videoStreamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.video_stream_id
     *
     * @param videoStreamId the value for t_image.video_stream_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setVideoStreamId(Long videoStreamId) {
        this.videoStreamId = videoStreamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.image_type_id
     *
     * @return the value of t_image.image_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Long getImageTypeId() {
        return imageTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.image_type_id
     *
     * @param imageTypeId the value for t_image.image_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setImageTypeId(Long imageTypeId) {
        this.imageTypeId = imageTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.detail
     *
     * @return the value of t_image.detail
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.detail
     *
     * @param detail the value for t_image.detail
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}