package com.zhuanjingkj.stpbe.platform.domain;

public class ImgType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_type.img_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    private Integer imgTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_type.img_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String imgTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_type.img_type_id
     *
     * @return the value of t_img_type.img_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Integer getImgTypeId() {
        return imgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_type.img_type_id
     *
     * @param imgTypeId the value for t_img_type.img_type_id
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setImgTypeId(Integer imgTypeId) {
        this.imgTypeId = imgTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_type.img_type_name
     *
     * @return the value of t_img_type.img_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getImgTypeName() {
        return imgTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_type.img_type_name
     *
     * @param imgTypeName the value for t_img_type.img_type_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setImgTypeName(String imgTypeName) {
        this.imgTypeName = imgTypeName == null ? null : imgTypeName.trim();
    }
}