package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class ImgTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public ImgTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgTypeIdIsNull() {
            addCriterion("img_type_id is null");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdIsNotNull() {
            addCriterion("img_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdEqualTo(Integer value) {
            addCriterion("img_type_id =", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdNotEqualTo(Integer value) {
            addCriterion("img_type_id <>", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdGreaterThan(Integer value) {
            addCriterion("img_type_id >", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("img_type_id >=", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdLessThan(Integer value) {
            addCriterion("img_type_id <", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("img_type_id <=", value, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdIn(List<Integer> values) {
            addCriterion("img_type_id in", values, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdNotIn(List<Integer> values) {
            addCriterion("img_type_id not in", values, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("img_type_id between", value1, value2, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("img_type_id not between", value1, value2, "imgTypeId");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameIsNull() {
            addCriterion("img_type_name is null");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameIsNotNull() {
            addCriterion("img_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameEqualTo(String value) {
            addCriterion("img_type_name =", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameNotEqualTo(String value) {
            addCriterion("img_type_name <>", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameGreaterThan(String value) {
            addCriterion("img_type_name >", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("img_type_name >=", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameLessThan(String value) {
            addCriterion("img_type_name <", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameLessThanOrEqualTo(String value) {
            addCriterion("img_type_name <=", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameLike(String value) {
            addCriterion("img_type_name like", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameNotLike(String value) {
            addCriterion("img_type_name not like", value, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameIn(List<String> values) {
            addCriterion("img_type_name in", values, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameNotIn(List<String> values) {
            addCriterion("img_type_name not in", values, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameBetween(String value1, String value2) {
            addCriterion("img_type_name between", value1, value2, "imgTypeName");
            return (Criteria) this;
        }

        public Criteria andImgTypeNameNotBetween(String value1, String value2) {
            addCriterion("img_type_name not between", value1, value2, "imgTypeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_type
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}