package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class ImgVaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public ImgVaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgVaIdIsNull() {
            addCriterion("img_va_id is null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIsNotNull() {
            addCriterion("img_va_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdEqualTo(Long value) {
            addCriterion("img_va_id =", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotEqualTo(Long value) {
            addCriterion("img_va_id <>", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThan(Long value) {
            addCriterion("img_va_id >", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("img_va_id >=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThan(Long value) {
            addCriterion("img_va_id <", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThanOrEqualTo(Long value) {
            addCriterion("img_va_id <=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIn(List<Long> values) {
            addCriterion("img_va_id in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotIn(List<Long> values) {
            addCriterion("img_va_id not in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdBetween(Long value1, Long value2) {
            addCriterion("img_va_id between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotBetween(Long value1, Long value2) {
            addCriterion("img_va_id not between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImageIdIsNull() {
            addCriterion("image_id is null");
            return (Criteria) this;
        }

        public Criteria andImageIdIsNotNull() {
            addCriterion("image_id is not null");
            return (Criteria) this;
        }

        public Criteria andImageIdEqualTo(Long value) {
            addCriterion("image_id =", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotEqualTo(Long value) {
            addCriterion("image_id <>", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdGreaterThan(Long value) {
            addCriterion("image_id >", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("image_id >=", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdLessThan(Long value) {
            addCriterion("image_id <", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdLessThanOrEqualTo(Long value) {
            addCriterion("image_id <=", value, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdIn(List<Long> values) {
            addCriterion("image_id in", values, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotIn(List<Long> values) {
            addCriterion("image_id not in", values, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdBetween(Long value1, Long value2) {
            addCriterion("image_id between", value1, value2, "imageId");
            return (Criteria) this;
        }

        public Criteria andImageIdNotBetween(Long value1, Long value2) {
            addCriterion("image_id not between", value1, value2, "imageId");
            return (Criteria) this;
        }

        public Criteria andSxhIsNull() {
            addCriterion("sxh is null");
            return (Criteria) this;
        }

        public Criteria andSxhIsNotNull() {
            addCriterion("sxh is not null");
            return (Criteria) this;
        }

        public Criteria andSxhEqualTo(Byte value) {
            addCriterion("sxh =", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhNotEqualTo(Byte value) {
            addCriterion("sxh <>", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhGreaterThan(Byte value) {
            addCriterion("sxh >", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhGreaterThanOrEqualTo(Byte value) {
            addCriterion("sxh >=", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhLessThan(Byte value) {
            addCriterion("sxh <", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhLessThanOrEqualTo(Byte value) {
            addCriterion("sxh <=", value, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhIn(List<Byte> values) {
            addCriterion("sxh in", values, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhNotIn(List<Byte> values) {
            addCriterion("sxh not in", values, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhBetween(Byte value1, Byte value2) {
            addCriterion("sxh between", value1, value2, "sxh");
            return (Criteria) this;
        }

        public Criteria andSxhNotBetween(Byte value1, Byte value2) {
            addCriterion("sxh not between", value1, value2, "sxh");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeIsNull() {
            addCriterion("vehicle_code is null");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeIsNotNull() {
            addCriterion("vehicle_code is not null");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeEqualTo(String value) {
            addCriterion("vehicle_code =", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeNotEqualTo(String value) {
            addCriterion("vehicle_code <>", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeGreaterThan(String value) {
            addCriterion("vehicle_code >", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vehicle_code >=", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeLessThan(String value) {
            addCriterion("vehicle_code <", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeLessThanOrEqualTo(String value) {
            addCriterion("vehicle_code <=", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeLike(String value) {
            addCriterion("vehicle_code like", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeNotLike(String value) {
            addCriterion("vehicle_code not like", value, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeIn(List<String> values) {
            addCriterion("vehicle_code in", values, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeNotIn(List<String> values) {
            addCriterion("vehicle_code not in", values, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeBetween(String value1, String value2) {
            addCriterion("vehicle_code between", value1, value2, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andVehicleCodeNotBetween(String value1, String value2) {
            addCriterion("vehicle_code not between", value1, value2, "vehicleCode");
            return (Criteria) this;
        }

        public Criteria andRefImageIdIsNull() {
            addCriterion("ref_image_id is null");
            return (Criteria) this;
        }

        public Criteria andRefImageIdIsNotNull() {
            addCriterion("ref_image_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefImageIdEqualTo(Long value) {
            addCriterion("ref_image_id =", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdNotEqualTo(Long value) {
            addCriterion("ref_image_id <>", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdGreaterThan(Long value) {
            addCriterion("ref_image_id >", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ref_image_id >=", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdLessThan(Long value) {
            addCriterion("ref_image_id <", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdLessThanOrEqualTo(Long value) {
            addCriterion("ref_image_id <=", value, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdIn(List<Long> values) {
            addCriterion("ref_image_id in", values, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdNotIn(List<Long> values) {
            addCriterion("ref_image_id not in", values, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdBetween(Long value1, Long value2) {
            addCriterion("ref_image_id between", value1, value2, "refImageId");
            return (Criteria) this;
        }

        public Criteria andRefImageIdNotBetween(Long value1, Long value2) {
            addCriterion("ref_image_id not between", value1, value2, "refImageId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}