package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ImgVaHptzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public ImgVaHptzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImageVaIdIsNull() {
            addCriterion("image_va_id is null");
            return (Criteria) this;
        }

        public Criteria andImageVaIdIsNotNull() {
            addCriterion("image_va_id is not null");
            return (Criteria) this;
        }

        public Criteria andImageVaIdEqualTo(Long value) {
            addCriterion("image_va_id =", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdNotEqualTo(Long value) {
            addCriterion("image_va_id <>", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdGreaterThan(Long value) {
            addCriterion("image_va_id >", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("image_va_id >=", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdLessThan(Long value) {
            addCriterion("image_va_id <", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdLessThanOrEqualTo(Long value) {
            addCriterion("image_va_id <=", value, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdIn(List<Long> values) {
            addCriterion("image_va_id in", values, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdNotIn(List<Long> values) {
            addCriterion("image_va_id not in", values, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdBetween(Long value1, Long value2) {
            addCriterion("image_va_id between", value1, value2, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andImageVaIdNotBetween(Long value1, Long value2) {
            addCriterion("image_va_id not between", value1, value2, "imageVaId");
            return (Criteria) this;
        }

        public Criteria andHptzJsonIsNull() {
            addCriterion("hptz_json is null");
            return (Criteria) this;
        }

        public Criteria andHptzJsonIsNotNull() {
            addCriterion("hptz_json is not null");
            return (Criteria) this;
        }

        public Criteria andHptzJsonEqualTo(String value) {
            addCriterion("hptz_json =", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonNotEqualTo(String value) {
            addCriterion("hptz_json <>", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonGreaterThan(String value) {
            addCriterion("hptz_json >", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonGreaterThanOrEqualTo(String value) {
            addCriterion("hptz_json >=", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonLessThan(String value) {
            addCriterion("hptz_json <", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonLessThanOrEqualTo(String value) {
            addCriterion("hptz_json <=", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonLike(String value) {
            addCriterion("hptz_json like", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonNotLike(String value) {
            addCriterion("hptz_json not like", value, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonIn(List<String> values) {
            addCriterion("hptz_json in", values, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonNotIn(List<String> values) {
            addCriterion("hptz_json not in", values, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonBetween(String value1, String value2) {
            addCriterion("hptz_json between", value1, value2, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHptzJsonNotBetween(String value1, String value2) {
            addCriterion("hptz_json not between", value1, value2, "hptzJson");
            return (Criteria) this;
        }

        public Criteria andHpwzXIsNull() {
            addCriterion("hpwz_x is null");
            return (Criteria) this;
        }

        public Criteria andHpwzXIsNotNull() {
            addCriterion("hpwz_x is not null");
            return (Criteria) this;
        }

        public Criteria andHpwzXEqualTo(Integer value) {
            addCriterion("hpwz_x =", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXNotEqualTo(Integer value) {
            addCriterion("hpwz_x <>", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXGreaterThan(Integer value) {
            addCriterion("hpwz_x >", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpwz_x >=", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXLessThan(Integer value) {
            addCriterion("hpwz_x <", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXLessThanOrEqualTo(Integer value) {
            addCriterion("hpwz_x <=", value, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXIn(List<Integer> values) {
            addCriterion("hpwz_x in", values, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXNotIn(List<Integer> values) {
            addCriterion("hpwz_x not in", values, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_x between", value1, value2, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzXNotBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_x not between", value1, value2, "hpwzX");
            return (Criteria) this;
        }

        public Criteria andHpwzYIsNull() {
            addCriterion("hpwz_y is null");
            return (Criteria) this;
        }

        public Criteria andHpwzYIsNotNull() {
            addCriterion("hpwz_y is not null");
            return (Criteria) this;
        }

        public Criteria andHpwzYEqualTo(Integer value) {
            addCriterion("hpwz_y =", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYNotEqualTo(Integer value) {
            addCriterion("hpwz_y <>", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYGreaterThan(Integer value) {
            addCriterion("hpwz_y >", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpwz_y >=", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYLessThan(Integer value) {
            addCriterion("hpwz_y <", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYLessThanOrEqualTo(Integer value) {
            addCriterion("hpwz_y <=", value, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYIn(List<Integer> values) {
            addCriterion("hpwz_y in", values, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYNotIn(List<Integer> values) {
            addCriterion("hpwz_y not in", values, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_y between", value1, value2, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzYNotBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_y not between", value1, value2, "hpwzY");
            return (Criteria) this;
        }

        public Criteria andHpwzWIsNull() {
            addCriterion("hpwz_w is null");
            return (Criteria) this;
        }

        public Criteria andHpwzWIsNotNull() {
            addCriterion("hpwz_w is not null");
            return (Criteria) this;
        }

        public Criteria andHpwzWEqualTo(Integer value) {
            addCriterion("hpwz_w =", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWNotEqualTo(Integer value) {
            addCriterion("hpwz_w <>", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWGreaterThan(Integer value) {
            addCriterion("hpwz_w >", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpwz_w >=", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWLessThan(Integer value) {
            addCriterion("hpwz_w <", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWLessThanOrEqualTo(Integer value) {
            addCriterion("hpwz_w <=", value, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWIn(List<Integer> values) {
            addCriterion("hpwz_w in", values, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWNotIn(List<Integer> values) {
            addCriterion("hpwz_w not in", values, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_w between", value1, value2, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzWNotBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_w not between", value1, value2, "hpwzW");
            return (Criteria) this;
        }

        public Criteria andHpwzHIsNull() {
            addCriterion("hpwz_h is null");
            return (Criteria) this;
        }

        public Criteria andHpwzHIsNotNull() {
            addCriterion("hpwz_h is not null");
            return (Criteria) this;
        }

        public Criteria andHpwzHEqualTo(Integer value) {
            addCriterion("hpwz_h =", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHNotEqualTo(Integer value) {
            addCriterion("hpwz_h <>", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHGreaterThan(Integer value) {
            addCriterion("hpwz_h >", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpwz_h >=", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHLessThan(Integer value) {
            addCriterion("hpwz_h <", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHLessThanOrEqualTo(Integer value) {
            addCriterion("hpwz_h <=", value, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHIn(List<Integer> values) {
            addCriterion("hpwz_h in", values, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHNotIn(List<Integer> values) {
            addCriterion("hpwz_h not in", values, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_h between", value1, value2, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andHpwzHNotBetween(Integer value1, Integer value2) {
            addCriterion("hpwz_h not between", value1, value2, "hpwzH");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdIsNull() {
            addCriterion("va_hpzt_id is null");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdIsNotNull() {
            addCriterion("va_hpzt_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdEqualTo(Long value) {
            addCriterion("va_hpzt_id =", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdNotEqualTo(Long value) {
            addCriterion("va_hpzt_id <>", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdGreaterThan(Long value) {
            addCriterion("va_hpzt_id >", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_hpzt_id >=", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdLessThan(Long value) {
            addCriterion("va_hpzt_id <", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdLessThanOrEqualTo(Long value) {
            addCriterion("va_hpzt_id <=", value, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdIn(List<Long> values) {
            addCriterion("va_hpzt_id in", values, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdNotIn(List<Long> values) {
            addCriterion("va_hpzt_id not in", values, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdBetween(Long value1, Long value2) {
            addCriterion("va_hpzt_id between", value1, value2, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpztIdNotBetween(Long value1, Long value2) {
            addCriterion("va_hpzt_id not between", value1, value2, "vaHpztId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdIsNull() {
            addCriterion("va_hpzl_id is null");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdIsNotNull() {
            addCriterion("va_hpzl_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdEqualTo(Long value) {
            addCriterion("va_hpzl_id =", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdNotEqualTo(Long value) {
            addCriterion("va_hpzl_id <>", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdGreaterThan(Long value) {
            addCriterion("va_hpzl_id >", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_hpzl_id >=", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdLessThan(Long value) {
            addCriterion("va_hpzl_id <", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdLessThanOrEqualTo(Long value) {
            addCriterion("va_hpzl_id <=", value, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdIn(List<Long> values) {
            addCriterion("va_hpzl_id in", values, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdNotIn(List<Long> values) {
            addCriterion("va_hpzl_id not in", values, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdBetween(Long value1, Long value2) {
            addCriterion("va_hpzl_id between", value1, value2, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpzlIdNotBetween(Long value1, Long value2) {
            addCriterion("va_hpzl_id not between", value1, value2, "vaHpzlId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdIsNull() {
            addCriterion("va_hpys_id is null");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdIsNotNull() {
            addCriterion("va_hpys_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdEqualTo(Long value) {
            addCriterion("va_hpys_id =", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotEqualTo(Long value) {
            addCriterion("va_hpys_id <>", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdGreaterThan(Long value) {
            addCriterion("va_hpys_id >", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_hpys_id >=", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdLessThan(Long value) {
            addCriterion("va_hpys_id <", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdLessThanOrEqualTo(Long value) {
            addCriterion("va_hpys_id <=", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdIn(List<Long> values) {
            addCriterion("va_hpys_id in", values, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotIn(List<Long> values) {
            addCriterion("va_hpys_id not in", values, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdBetween(Long value1, Long value2) {
            addCriterion("va_hpys_id between", value1, value2, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotBetween(Long value1, Long value2) {
            addCriterion("va_hpys_id not between", value1, value2, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdIsNull() {
            addCriterion("va_hpgg_id is null");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdIsNotNull() {
            addCriterion("va_hpgg_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdEqualTo(Long value) {
            addCriterion("va_hpgg_id =", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdNotEqualTo(Long value) {
            addCriterion("va_hpgg_id <>", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdGreaterThan(Long value) {
            addCriterion("va_hpgg_id >", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_hpgg_id >=", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdLessThan(Long value) {
            addCriterion("va_hpgg_id <", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdLessThanOrEqualTo(Long value) {
            addCriterion("va_hpgg_id <=", value, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdIn(List<Long> values) {
            addCriterion("va_hpgg_id in", values, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdNotIn(List<Long> values) {
            addCriterion("va_hpgg_id not in", values, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdBetween(Long value1, Long value2) {
            addCriterion("va_hpgg_id between", value1, value2, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andVaHpggIdNotBetween(Long value1, Long value2) {
            addCriterion("va_hpgg_id not between", value1, value2, "vaHpggId");
            return (Criteria) this;
        }

        public Criteria andHphmIsNull() {
            addCriterion("hphm is null");
            return (Criteria) this;
        }

        public Criteria andHphmIsNotNull() {
            addCriterion("hphm is not null");
            return (Criteria) this;
        }

        public Criteria andHphmEqualTo(String value) {
            addCriterion("hphm =", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotEqualTo(String value) {
            addCriterion("hphm <>", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmGreaterThan(String value) {
            addCriterion("hphm >", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmGreaterThanOrEqualTo(String value) {
            addCriterion("hphm >=", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLessThan(String value) {
            addCriterion("hphm <", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLessThanOrEqualTo(String value) {
            addCriterion("hphm <=", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmLike(String value) {
            addCriterion("hphm like", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotLike(String value) {
            addCriterion("hphm not like", value, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmIn(List<String> values) {
            addCriterion("hphm in", values, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotIn(List<String> values) {
            addCriterion("hphm not in", values, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmBetween(String value1, String value2) {
            addCriterion("hphm between", value1, value2, "hphm");
            return (Criteria) this;
        }

        public Criteria andHphmNotBetween(String value1, String value2) {
            addCriterion("hphm not between", value1, value2, "hphm");
            return (Criteria) this;
        }

        public Criteria andHpkxdIsNull() {
            addCriterion("hpkxd is null");
            return (Criteria) this;
        }

        public Criteria andHpkxdIsNotNull() {
            addCriterion("hpkxd is not null");
            return (Criteria) this;
        }

        public Criteria andHpkxdEqualTo(Integer value) {
            addCriterion("hpkxd =", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdNotEqualTo(Integer value) {
            addCriterion("hpkxd <>", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdGreaterThan(Integer value) {
            addCriterion("hpkxd >", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hpkxd >=", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdLessThan(Integer value) {
            addCriterion("hpkxd <", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdLessThanOrEqualTo(Integer value) {
            addCriterion("hpkxd <=", value, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdIn(List<Integer> values) {
            addCriterion("hpkxd in", values, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdNotIn(List<Integer> values) {
            addCriterion("hpkxd not in", values, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdBetween(Integer value1, Integer value2) {
            addCriterion("hpkxd between", value1, value2, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andHpkxdNotBetween(Integer value1, Integer value2) {
            addCriterion("hpkxd not between", value1, value2, "hpkxd");
            return (Criteria) this;
        }

        public Criteria andYwlshpIsNull() {
            addCriterion("ywlshp is null");
            return (Criteria) this;
        }

        public Criteria andYwlshpIsNotNull() {
            addCriterion("ywlshp is not null");
            return (Criteria) this;
        }

        public Criteria andYwlshpEqualTo(Byte value) {
            addCriterion("ywlshp =", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpNotEqualTo(Byte value) {
            addCriterion("ywlshp <>", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpGreaterThan(Byte value) {
            addCriterion("ywlshp >", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpGreaterThanOrEqualTo(Byte value) {
            addCriterion("ywlshp >=", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpLessThan(Byte value) {
            addCriterion("ywlshp <", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpLessThanOrEqualTo(Byte value) {
            addCriterion("ywlshp <=", value, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpIn(List<Byte> values) {
            addCriterion("ywlshp in", values, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpNotIn(List<Byte> values) {
            addCriterion("ywlshp not in", values, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpBetween(Byte value1, Byte value2) {
            addCriterion("ywlshp between", value1, value2, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andYwlshpNotBetween(Byte value1, Byte value2) {
            addCriterion("ywlshp not between", value1, value2, "ywlshp");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_hptz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}