package com.zhuanjingkj.stpbe.platform.domain;

public class ImgVa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va.img_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long imgVaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va.sxh
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Byte sxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va.vehicle_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vehicleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va.ref_image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long refImageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va.img_va_id
     *
     * @return the value of t_img_va.img_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getImgVaId() {
        return imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va.img_va_id
     *
     * @param imgVaId the value for t_img_va.img_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setImgVaId(Long imgVaId) {
        this.imgVaId = imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va.image_id
     *
     * @return the value of t_img_va.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va.image_id
     *
     * @param imageId the value for t_img_va.image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va.sxh
     *
     * @return the value of t_img_va.sxh
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Byte getSxh() {
        return sxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va.sxh
     *
     * @param sxh the value for t_img_va.sxh
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setSxh(Byte sxh) {
        this.sxh = sxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va.vehicle_code
     *
     * @return the value of t_img_va.vehicle_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVehicleCode() {
        return vehicleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va.vehicle_code
     *
     * @param vehicleCode the value for t_img_va.vehicle_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVehicleCode(String vehicleCode) {
        this.vehicleCode = vehicleCode == null ? null : vehicleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va.ref_image_id
     *
     * @return the value of t_img_va.ref_image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getRefImageId() {
        return refImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va.ref_image_id
     *
     * @param refImageId the value for t_img_va.ref_image_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setRefImageId(Long refImageId) {
        this.refImageId = refImageId;
    }
}