package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class ImgVaWztzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public ImgVaWztzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgVaIdIsNull() {
            addCriterion("img_va_id is null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIsNotNull() {
            addCriterion("img_va_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdEqualTo(Long value) {
            addCriterion("img_va_id =", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotEqualTo(Long value) {
            addCriterion("img_va_id <>", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThan(Long value) {
            addCriterion("img_va_id >", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("img_va_id >=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThan(Long value) {
            addCriterion("img_va_id <", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThanOrEqualTo(Long value) {
            addCriterion("img_va_id <=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIn(List<Long> values) {
            addCriterion("img_va_id in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotIn(List<Long> values) {
            addCriterion("img_va_id not in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdBetween(Long value1, Long value2) {
            addCriterion("img_va_id between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotBetween(Long value1, Long value2) {
            addCriterion("img_va_id not between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andWztzJsonIsNull() {
            addCriterion("wztz_json is null");
            return (Criteria) this;
        }

        public Criteria andWztzJsonIsNotNull() {
            addCriterion("wztz_json is not null");
            return (Criteria) this;
        }

        public Criteria andWztzJsonEqualTo(String value) {
            addCriterion("wztz_json =", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonNotEqualTo(String value) {
            addCriterion("wztz_json <>", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonGreaterThan(String value) {
            addCriterion("wztz_json >", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonGreaterThanOrEqualTo(String value) {
            addCriterion("wztz_json >=", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonLessThan(String value) {
            addCriterion("wztz_json <", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonLessThanOrEqualTo(String value) {
            addCriterion("wztz_json <=", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonLike(String value) {
            addCriterion("wztz_json like", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonNotLike(String value) {
            addCriterion("wztz_json not like", value, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonIn(List<String> values) {
            addCriterion("wztz_json in", values, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonNotIn(List<String> values) {
            addCriterion("wztz_json not in", values, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonBetween(String value1, String value2) {
            addCriterion("wztz_json between", value1, value2, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andWztzJsonNotBetween(String value1, String value2) {
            addCriterion("wztz_json not between", value1, value2, "wztzJson");
            return (Criteria) this;
        }

        public Criteria andClwzXIsNull() {
            addCriterion("clwz_x is null");
            return (Criteria) this;
        }

        public Criteria andClwzXIsNotNull() {
            addCriterion("clwz_x is not null");
            return (Criteria) this;
        }

        public Criteria andClwzXEqualTo(Integer value) {
            addCriterion("clwz_x =", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXNotEqualTo(Integer value) {
            addCriterion("clwz_x <>", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXGreaterThan(Integer value) {
            addCriterion("clwz_x >", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXGreaterThanOrEqualTo(Integer value) {
            addCriterion("clwz_x >=", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXLessThan(Integer value) {
            addCriterion("clwz_x <", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXLessThanOrEqualTo(Integer value) {
            addCriterion("clwz_x <=", value, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXIn(List<Integer> values) {
            addCriterion("clwz_x in", values, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXNotIn(List<Integer> values) {
            addCriterion("clwz_x not in", values, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXBetween(Integer value1, Integer value2) {
            addCriterion("clwz_x between", value1, value2, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzXNotBetween(Integer value1, Integer value2) {
            addCriterion("clwz_x not between", value1, value2, "clwzX");
            return (Criteria) this;
        }

        public Criteria andClwzYIsNull() {
            addCriterion("clwz_y is null");
            return (Criteria) this;
        }

        public Criteria andClwzYIsNotNull() {
            addCriterion("clwz_y is not null");
            return (Criteria) this;
        }

        public Criteria andClwzYEqualTo(Integer value) {
            addCriterion("clwz_y =", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYNotEqualTo(Integer value) {
            addCriterion("clwz_y <>", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYGreaterThan(Integer value) {
            addCriterion("clwz_y >", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYGreaterThanOrEqualTo(Integer value) {
            addCriterion("clwz_y >=", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYLessThan(Integer value) {
            addCriterion("clwz_y <", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYLessThanOrEqualTo(Integer value) {
            addCriterion("clwz_y <=", value, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYIn(List<Integer> values) {
            addCriterion("clwz_y in", values, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYNotIn(List<Integer> values) {
            addCriterion("clwz_y not in", values, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYBetween(Integer value1, Integer value2) {
            addCriterion("clwz_y between", value1, value2, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzYNotBetween(Integer value1, Integer value2) {
            addCriterion("clwz_y not between", value1, value2, "clwzY");
            return (Criteria) this;
        }

        public Criteria andClwzWIsNull() {
            addCriterion("clwz_w is null");
            return (Criteria) this;
        }

        public Criteria andClwzWIsNotNull() {
            addCriterion("clwz_w is not null");
            return (Criteria) this;
        }

        public Criteria andClwzWEqualTo(Integer value) {
            addCriterion("clwz_w =", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWNotEqualTo(Integer value) {
            addCriterion("clwz_w <>", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWGreaterThan(Integer value) {
            addCriterion("clwz_w >", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWGreaterThanOrEqualTo(Integer value) {
            addCriterion("clwz_w >=", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWLessThan(Integer value) {
            addCriterion("clwz_w <", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWLessThanOrEqualTo(Integer value) {
            addCriterion("clwz_w <=", value, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWIn(List<Integer> values) {
            addCriterion("clwz_w in", values, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWNotIn(List<Integer> values) {
            addCriterion("clwz_w not in", values, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWBetween(Integer value1, Integer value2) {
            addCriterion("clwz_w between", value1, value2, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzWNotBetween(Integer value1, Integer value2) {
            addCriterion("clwz_w not between", value1, value2, "clwzW");
            return (Criteria) this;
        }

        public Criteria andClwzHIsNull() {
            addCriterion("clwz_h is null");
            return (Criteria) this;
        }

        public Criteria andClwzHIsNotNull() {
            addCriterion("clwz_h is not null");
            return (Criteria) this;
        }

        public Criteria andClwzHEqualTo(Integer value) {
            addCriterion("clwz_h =", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHNotEqualTo(Integer value) {
            addCriterion("clwz_h <>", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHGreaterThan(Integer value) {
            addCriterion("clwz_h >", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHGreaterThanOrEqualTo(Integer value) {
            addCriterion("clwz_h >=", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHLessThan(Integer value) {
            addCriterion("clwz_h <", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHLessThanOrEqualTo(Integer value) {
            addCriterion("clwz_h <=", value, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHIn(List<Integer> values) {
            addCriterion("clwz_h in", values, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHNotIn(List<Integer> values) {
            addCriterion("clwz_h not in", values, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHBetween(Integer value1, Integer value2) {
            addCriterion("clwz_h between", value1, value2, "clwzH");
            return (Criteria) this;
        }

        public Criteria andClwzHNotBetween(Integer value1, Integer value2) {
            addCriterion("clwz_h not between", value1, value2, "clwzH");
            return (Criteria) this;
        }

        public Criteria andPsfxIsNull() {
            addCriterion("psfx is null");
            return (Criteria) this;
        }

        public Criteria andPsfxIsNotNull() {
            addCriterion("psfx is not null");
            return (Criteria) this;
        }

        public Criteria andPsfxEqualTo(Byte value) {
            addCriterion("psfx =", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxNotEqualTo(Byte value) {
            addCriterion("psfx <>", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxGreaterThan(Byte value) {
            addCriterion("psfx >", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxGreaterThanOrEqualTo(Byte value) {
            addCriterion("psfx >=", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxLessThan(Byte value) {
            addCriterion("psfx <", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxLessThanOrEqualTo(Byte value) {
            addCriterion("psfx <=", value, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxIn(List<Byte> values) {
            addCriterion("psfx in", values, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxNotIn(List<Byte> values) {
            addCriterion("psfx not in", values, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxBetween(Byte value1, Byte value2) {
            addCriterion("psfx between", value1, value2, "psfx");
            return (Criteria) this;
        }

        public Criteria andPsfxNotBetween(Byte value1, Byte value2) {
            addCriterion("psfx not between", value1, value2, "psfx");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}