package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class ImgVaCxtzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public ImgVaCxtzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImgVaIdIsNull() {
            addCriterion("img_va_id is null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIsNotNull() {
            addCriterion("img_va_id is not null");
            return (Criteria) this;
        }

        public Criteria andImgVaIdEqualTo(Long value) {
            addCriterion("img_va_id =", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotEqualTo(Long value) {
            addCriterion("img_va_id <>", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThan(Long value) {
            addCriterion("img_va_id >", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("img_va_id >=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThan(Long value) {
            addCriterion("img_va_id <", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdLessThanOrEqualTo(Long value) {
            addCriterion("img_va_id <=", value, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdIn(List<Long> values) {
            addCriterion("img_va_id in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotIn(List<Long> values) {
            addCriterion("img_va_id not in", values, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdBetween(Long value1, Long value2) {
            addCriterion("img_va_id between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andImgVaIdNotBetween(Long value1, Long value2) {
            addCriterion("img_va_id not between", value1, value2, "imgVaId");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonIsNull() {
            addCriterion("cxtz_json is null");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonIsNotNull() {
            addCriterion("cxtz_json is not null");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonEqualTo(String value) {
            addCriterion("cxtz_json =", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonNotEqualTo(String value) {
            addCriterion("cxtz_json <>", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonGreaterThan(String value) {
            addCriterion("cxtz_json >", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonGreaterThanOrEqualTo(String value) {
            addCriterion("cxtz_json >=", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonLessThan(String value) {
            addCriterion("cxtz_json <", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonLessThanOrEqualTo(String value) {
            addCriterion("cxtz_json <=", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonLike(String value) {
            addCriterion("cxtz_json like", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonNotLike(String value) {
            addCriterion("cxtz_json not like", value, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonIn(List<String> values) {
            addCriterion("cxtz_json in", values, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonNotIn(List<String> values) {
            addCriterion("cxtz_json not in", values, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonBetween(String value1, String value2) {
            addCriterion("cxtz_json between", value1, value2, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andCxtzJsonNotBetween(String value1, String value2) {
            addCriterion("cxtz_json not between", value1, value2, "cxtzJson");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdIsNull() {
            addCriterion("va_cllxfl_id is null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdIsNotNull() {
            addCriterion("va_cllxfl_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdEqualTo(Integer value) {
            addCriterion("va_cllxfl_id =", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotEqualTo(Integer value) {
            addCriterion("va_cllxfl_id <>", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdGreaterThan(Integer value) {
            addCriterion("va_cllxfl_id >", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("va_cllxfl_id >=", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdLessThan(Integer value) {
            addCriterion("va_cllxfl_id <", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdLessThanOrEqualTo(Integer value) {
            addCriterion("va_cllxfl_id <=", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdIn(List<Integer> values) {
            addCriterion("va_cllxfl_id in", values, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotIn(List<Integer> values) {
            addCriterion("va_cllxfl_id not in", values, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdBetween(Integer value1, Integer value2) {
            addCriterion("va_cllxfl_id between", value1, value2, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotBetween(Integer value1, Integer value2) {
            addCriterion("va_cllxfl_id not between", value1, value2, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdIsNull() {
            addCriterion("va_cllxzfl_id is null");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdIsNotNull() {
            addCriterion("va_cllxzfl_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdEqualTo(Byte value) {
            addCriterion("va_cllxzfl_id =", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdNotEqualTo(Byte value) {
            addCriterion("va_cllxzfl_id <>", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdGreaterThan(Byte value) {
            addCriterion("va_cllxzfl_id >", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdGreaterThanOrEqualTo(Byte value) {
            addCriterion("va_cllxzfl_id >=", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdLessThan(Byte value) {
            addCriterion("va_cllxzfl_id <", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdLessThanOrEqualTo(Byte value) {
            addCriterion("va_cllxzfl_id <=", value, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdIn(List<Byte> values) {
            addCriterion("va_cllxzfl_id in", values, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdNotIn(List<Byte> values) {
            addCriterion("va_cllxzfl_id not in", values, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdBetween(Byte value1, Byte value2) {
            addCriterion("va_cllxzfl_id between", value1, value2, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxzflIdNotBetween(Byte value1, Byte value2) {
            addCriterion("va_cllxzfl_id not between", value1, value2, "vaCllxzflId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdIsNull() {
            addCriterion("va_csys_id is null");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdIsNotNull() {
            addCriterion("va_csys_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdEqualTo(Integer value) {
            addCriterion("va_csys_id =", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdNotEqualTo(Integer value) {
            addCriterion("va_csys_id <>", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdGreaterThan(Integer value) {
            addCriterion("va_csys_id >", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("va_csys_id >=", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdLessThan(Integer value) {
            addCriterion("va_csys_id <", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdLessThanOrEqualTo(Integer value) {
            addCriterion("va_csys_id <=", value, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdIn(List<Integer> values) {
            addCriterion("va_csys_id in", values, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdNotIn(List<Integer> values) {
            addCriterion("va_csys_id not in", values, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdBetween(Integer value1, Integer value2) {
            addCriterion("va_csys_id between", value1, value2, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaCsysIdNotBetween(Integer value1, Integer value2) {
            addCriterion("va_csys_id not between", value1, value2, "vaCsysId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdIsNull() {
            addCriterion("va_clpp_id is null");
            return (Criteria) this;
        }

        public Criteria andVaClppIdIsNotNull() {
            addCriterion("va_clpp_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaClppIdEqualTo(Long value) {
            addCriterion("va_clpp_id =", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdNotEqualTo(Long value) {
            addCriterion("va_clpp_id <>", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdGreaterThan(Long value) {
            addCriterion("va_clpp_id >", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_clpp_id >=", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdLessThan(Long value) {
            addCriterion("va_clpp_id <", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdLessThanOrEqualTo(Long value) {
            addCriterion("va_clpp_id <=", value, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdIn(List<Long> values) {
            addCriterion("va_clpp_id in", values, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdNotIn(List<Long> values) {
            addCriterion("va_clpp_id not in", values, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdBetween(Long value1, Long value2) {
            addCriterion("va_clpp_id between", value1, value2, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaClppIdNotBetween(Long value1, Long value2) {
            addCriterion("va_clpp_id not between", value1, value2, "vaClppId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdIsNull() {
            addCriterion("va_ppcx_id is null");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdIsNotNull() {
            addCriterion("va_ppcx_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdEqualTo(Long value) {
            addCriterion("va_ppcx_id =", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdNotEqualTo(Long value) {
            addCriterion("va_ppcx_id <>", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdGreaterThan(Long value) {
            addCriterion("va_ppcx_id >", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_ppcx_id >=", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdLessThan(Long value) {
            addCriterion("va_ppcx_id <", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdLessThanOrEqualTo(Long value) {
            addCriterion("va_ppcx_id <=", value, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdIn(List<Long> values) {
            addCriterion("va_ppcx_id in", values, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdNotIn(List<Long> values) {
            addCriterion("va_ppcx_id not in", values, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdBetween(Long value1, Long value2) {
            addCriterion("va_ppcx_id between", value1, value2, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaPpcxIdNotBetween(Long value1, Long value2) {
            addCriterion("va_ppcx_id not between", value1, value2, "vaPpcxId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdIsNull() {
            addCriterion("va_cxnk_id is null");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdIsNotNull() {
            addCriterion("va_cxnk_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdEqualTo(Long value) {
            addCriterion("va_cxnk_id =", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdNotEqualTo(Long value) {
            addCriterion("va_cxnk_id <>", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdGreaterThan(Long value) {
            addCriterion("va_cxnk_id >", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdGreaterThanOrEqualTo(Long value) {
            addCriterion("va_cxnk_id >=", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdLessThan(Long value) {
            addCriterion("va_cxnk_id <", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdLessThanOrEqualTo(Long value) {
            addCriterion("va_cxnk_id <=", value, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdIn(List<Long> values) {
            addCriterion("va_cxnk_id in", values, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdNotIn(List<Long> values) {
            addCriterion("va_cxnk_id not in", values, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdBetween(Long value1, Long value2) {
            addCriterion("va_cxnk_id between", value1, value2, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andVaCxnkIdNotBetween(Long value1, Long value2) {
            addCriterion("va_cxnk_id not between", value1, value2, "vaCxnkId");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdIsNull() {
            addCriterion("ppxhkxd is null");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdIsNotNull() {
            addCriterion("ppxhkxd is not null");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdEqualTo(Integer value) {
            addCriterion("ppxhkxd =", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdNotEqualTo(Integer value) {
            addCriterion("ppxhkxd <>", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdGreaterThan(Integer value) {
            addCriterion("ppxhkxd >", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ppxhkxd >=", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdLessThan(Integer value) {
            addCriterion("ppxhkxd <", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdLessThanOrEqualTo(Integer value) {
            addCriterion("ppxhkxd <=", value, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdIn(List<Integer> values) {
            addCriterion("ppxhkxd in", values, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdNotIn(List<Integer> values) {
            addCriterion("ppxhkxd not in", values, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdBetween(Integer value1, Integer value2) {
            addCriterion("ppxhkxd between", value1, value2, "ppxhkxd");
            return (Criteria) this;
        }

        public Criteria andPpxhkxdNotBetween(Integer value1, Integer value2) {
            addCriterion("ppxhkxd not between", value1, value2, "ppxhkxd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_va_cxtz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}