package com.zhuanjingkj.stpbe.platform.domain;

import java.util.Date;

public class ImgVaHptz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.image_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long imageVaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hptz_json
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String hptzJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hpwz_x
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer hpwzX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hpwz_y
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer hpwzY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hpwz_w
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer hpwzW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hpwz_h
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer hpwzH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long vaHpztId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long vaHpzlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long vaHpysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Long vaHpggId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hphm
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String hphm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.hpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer hpkxd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.ywlshp
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Byte ywlshp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.create_time
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_hptz.mwhpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String mwhpkxd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.image_va_id
     *
     * @return the value of t_img_va_hptz.image_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getImageVaId() {
        return imageVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.image_va_id
     *
     * @param imageVaId the value for t_img_va_hptz.image_va_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setImageVaId(Long imageVaId) {
        this.imageVaId = imageVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hptz_json
     *
     * @return the value of t_img_va_hptz.hptz_json
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getHptzJson() {
        return hptzJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hptz_json
     *
     * @param hptzJson the value for t_img_va_hptz.hptz_json
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHptzJson(String hptzJson) {
        this.hptzJson = hptzJson == null ? null : hptzJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hpwz_x
     *
     * @return the value of t_img_va_hptz.hpwz_x
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getHpwzX() {
        return hpwzX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hpwz_x
     *
     * @param hpwzX the value for t_img_va_hptz.hpwz_x
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHpwzX(Integer hpwzX) {
        this.hpwzX = hpwzX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hpwz_y
     *
     * @return the value of t_img_va_hptz.hpwz_y
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getHpwzY() {
        return hpwzY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hpwz_y
     *
     * @param hpwzY the value for t_img_va_hptz.hpwz_y
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHpwzY(Integer hpwzY) {
        this.hpwzY = hpwzY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hpwz_w
     *
     * @return the value of t_img_va_hptz.hpwz_w
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getHpwzW() {
        return hpwzW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hpwz_w
     *
     * @param hpwzW the value for t_img_va_hptz.hpwz_w
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHpwzW(Integer hpwzW) {
        this.hpwzW = hpwzW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hpwz_h
     *
     * @return the value of t_img_va_hptz.hpwz_h
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getHpwzH() {
        return hpwzH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hpwz_h
     *
     * @param hpwzH the value for t_img_va_hptz.hpwz_h
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHpwzH(Integer hpwzH) {
        this.hpwzH = hpwzH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.va_hpzt_id
     *
     * @return the value of t_img_va_hptz.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getVaHpztId() {
        return vaHpztId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.va_hpzt_id
     *
     * @param vaHpztId the value for t_img_va_hptz.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpztId(Long vaHpztId) {
        this.vaHpztId = vaHpztId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.va_hpzl_id
     *
     * @return the value of t_img_va_hptz.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getVaHpzlId() {
        return vaHpzlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.va_hpzl_id
     *
     * @param vaHpzlId the value for t_img_va_hptz.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpzlId(Long vaHpzlId) {
        this.vaHpzlId = vaHpzlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.va_hpys_id
     *
     * @return the value of t_img_va_hptz.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getVaHpysId() {
        return vaHpysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.va_hpys_id
     *
     * @param vaHpysId the value for t_img_va_hptz.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpysId(Long vaHpysId) {
        this.vaHpysId = vaHpysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.va_hpgg_id
     *
     * @return the value of t_img_va_hptz.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Long getVaHpggId() {
        return vaHpggId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.va_hpgg_id
     *
     * @param vaHpggId the value for t_img_va_hptz.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpggId(Long vaHpggId) {
        this.vaHpggId = vaHpggId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hphm
     *
     * @return the value of t_img_va_hptz.hphm
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getHphm() {
        return hphm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hphm
     *
     * @param hphm the value for t_img_va_hptz.hphm
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHphm(String hphm) {
        this.hphm = hphm == null ? null : hphm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.hpkxd
     *
     * @return the value of t_img_va_hptz.hpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getHpkxd() {
        return hpkxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.hpkxd
     *
     * @param hpkxd the value for t_img_va_hptz.hpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setHpkxd(Integer hpkxd) {
        this.hpkxd = hpkxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.ywlshp
     *
     * @return the value of t_img_va_hptz.ywlshp
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Byte getYwlshp() {
        return ywlshp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.ywlshp
     *
     * @param ywlshp the value for t_img_va_hptz.ywlshp
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setYwlshp(Byte ywlshp) {
        this.ywlshp = ywlshp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.create_time
     *
     * @return the value of t_img_va_hptz.create_time
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.create_time
     *
     * @param createTime the value for t_img_va_hptz.create_time
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_hptz.mwhpkxd
     *
     * @return the value of t_img_va_hptz.mwhpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getMwhpkxd() {
        return mwhpkxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_hptz.mwhpkxd
     *
     * @param mwhpkxd the value for t_img_va_hptz.mwhpkxd
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setMwhpkxd(String mwhpkxd) {
        this.mwhpkxd = mwhpkxd == null ? null : mwhpkxd.trim();
    }
}