package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class VaCllxflExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public VaCllxflExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVaCllxflIdIsNull() {
            addCriterion("va_cllxfl_id is null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdIsNotNull() {
            addCriterion("va_cllxfl_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdEqualTo(Integer value) {
            addCriterion("va_cllxfl_id =", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotEqualTo(Integer value) {
            addCriterion("va_cllxfl_id <>", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdGreaterThan(Integer value) {
            addCriterion("va_cllxfl_id >", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("va_cllxfl_id >=", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdLessThan(Integer value) {
            addCriterion("va_cllxfl_id <", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdLessThanOrEqualTo(Integer value) {
            addCriterion("va_cllxfl_id <=", value, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdIn(List<Integer> values) {
            addCriterion("va_cllxfl_id in", values, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotIn(List<Integer> values) {
            addCriterion("va_cllxfl_id not in", values, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdBetween(Integer value1, Integer value2) {
            addCriterion("va_cllxfl_id between", value1, value2, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflIdNotBetween(Integer value1, Integer value2) {
            addCriterion("va_cllxfl_id not between", value1, value2, "vaCllxflId");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeIsNull() {
            addCriterion("va_cllxfl_code is null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeIsNotNull() {
            addCriterion("va_cllxfl_code is not null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeEqualTo(String value) {
            addCriterion("va_cllxfl_code =", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeNotEqualTo(String value) {
            addCriterion("va_cllxfl_code <>", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeGreaterThan(String value) {
            addCriterion("va_cllxfl_code >", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeGreaterThanOrEqualTo(String value) {
            addCriterion("va_cllxfl_code >=", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeLessThan(String value) {
            addCriterion("va_cllxfl_code <", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeLessThanOrEqualTo(String value) {
            addCriterion("va_cllxfl_code <=", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeLike(String value) {
            addCriterion("va_cllxfl_code like", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeNotLike(String value) {
            addCriterion("va_cllxfl_code not like", value, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeIn(List<String> values) {
            addCriterion("va_cllxfl_code in", values, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeNotIn(List<String> values) {
            addCriterion("va_cllxfl_code not in", values, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeBetween(String value1, String value2) {
            addCriterion("va_cllxfl_code between", value1, value2, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflCodeNotBetween(String value1, String value2) {
            addCriterion("va_cllxfl_code not between", value1, value2, "vaCllxflCode");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameIsNull() {
            addCriterion("va_cllxfl_name is null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameIsNotNull() {
            addCriterion("va_cllxfl_name is not null");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameEqualTo(String value) {
            addCriterion("va_cllxfl_name =", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameNotEqualTo(String value) {
            addCriterion("va_cllxfl_name <>", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameGreaterThan(String value) {
            addCriterion("va_cllxfl_name >", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameGreaterThanOrEqualTo(String value) {
            addCriterion("va_cllxfl_name >=", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameLessThan(String value) {
            addCriterion("va_cllxfl_name <", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameLessThanOrEqualTo(String value) {
            addCriterion("va_cllxfl_name <=", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameLike(String value) {
            addCriterion("va_cllxfl_name like", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameNotLike(String value) {
            addCriterion("va_cllxfl_name not like", value, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameIn(List<String> values) {
            addCriterion("va_cllxfl_name in", values, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameNotIn(List<String> values) {
            addCriterion("va_cllxfl_name not in", values, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameBetween(String value1, String value2) {
            addCriterion("va_cllxfl_name between", value1, value2, "vaCllxflName");
            return (Criteria) this;
        }

        public Criteria andVaCllxflNameNotBetween(String value1, String value2) {
            addCriterion("va_cllxfl_name not between", value1, value2, "vaCllxflName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}