package com.zhuanjingkj.stpbe.platform.domain;

public class VaCsys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_csys.va_csys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer vaCsysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_csys.va_csys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaCsysCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_csys.va_csys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaCsysName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_csys.va_csys_id
     *
     * @return the value of t_va_csys.va_csys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getVaCsysId() {
        return vaCsysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_csys.va_csys_id
     *
     * @param vaCsysId the value for t_va_csys.va_csys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaCsysId(Integer vaCsysId) {
        this.vaCsysId = vaCsysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_csys.va_csys_code
     *
     * @return the value of t_va_csys.va_csys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaCsysCode() {
        return vaCsysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_csys.va_csys_code
     *
     * @param vaCsysCode the value for t_va_csys.va_csys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaCsysCode(String vaCsysCode) {
        this.vaCsysCode = vaCsysCode == null ? null : vaCsysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_csys.va_csys_name
     *
     * @return the value of t_va_csys.va_csys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaCsysName() {
        return vaCsysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_csys.va_csys_name
     *
     * @param vaCsysName the value for t_va_csys.va_csys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaCsysName(String vaCsysName) {
        this.vaCsysName = vaCsysName == null ? null : vaCsysName.trim();
    }
}