package com.zhuanjingkj.stpbe.platform.domain;

import java.util.ArrayList;
import java.util.List;

public class VaHpysExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public VaHpysExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVaHpysIdIsNull() {
            addCriterion("va_hpys_id is null");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdIsNotNull() {
            addCriterion("va_hpys_id is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdEqualTo(Integer value) {
            addCriterion("va_hpys_id =", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotEqualTo(Integer value) {
            addCriterion("va_hpys_id <>", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdGreaterThan(Integer value) {
            addCriterion("va_hpys_id >", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("va_hpys_id >=", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdLessThan(Integer value) {
            addCriterion("va_hpys_id <", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdLessThanOrEqualTo(Integer value) {
            addCriterion("va_hpys_id <=", value, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdIn(List<Integer> values) {
            addCriterion("va_hpys_id in", values, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotIn(List<Integer> values) {
            addCriterion("va_hpys_id not in", values, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdBetween(Integer value1, Integer value2) {
            addCriterion("va_hpys_id between", value1, value2, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysIdNotBetween(Integer value1, Integer value2) {
            addCriterion("va_hpys_id not between", value1, value2, "vaHpysId");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeIsNull() {
            addCriterion("va_hpys_code is null");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeIsNotNull() {
            addCriterion("va_hpys_code is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeEqualTo(String value) {
            addCriterion("va_hpys_code =", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeNotEqualTo(String value) {
            addCriterion("va_hpys_code <>", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeGreaterThan(String value) {
            addCriterion("va_hpys_code >", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeGreaterThanOrEqualTo(String value) {
            addCriterion("va_hpys_code >=", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeLessThan(String value) {
            addCriterion("va_hpys_code <", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeLessThanOrEqualTo(String value) {
            addCriterion("va_hpys_code <=", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeLike(String value) {
            addCriterion("va_hpys_code like", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeNotLike(String value) {
            addCriterion("va_hpys_code not like", value, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeIn(List<String> values) {
            addCriterion("va_hpys_code in", values, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeNotIn(List<String> values) {
            addCriterion("va_hpys_code not in", values, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeBetween(String value1, String value2) {
            addCriterion("va_hpys_code between", value1, value2, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysCodeNotBetween(String value1, String value2) {
            addCriterion("va_hpys_code not between", value1, value2, "vaHpysCode");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameIsNull() {
            addCriterion("va_hpys_name is null");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameIsNotNull() {
            addCriterion("va_hpys_name is not null");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameEqualTo(String value) {
            addCriterion("va_hpys_name =", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameNotEqualTo(String value) {
            addCriterion("va_hpys_name <>", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameGreaterThan(String value) {
            addCriterion("va_hpys_name >", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameGreaterThanOrEqualTo(String value) {
            addCriterion("va_hpys_name >=", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameLessThan(String value) {
            addCriterion("va_hpys_name <", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameLessThanOrEqualTo(String value) {
            addCriterion("va_hpys_name <=", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameLike(String value) {
            addCriterion("va_hpys_name like", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameNotLike(String value) {
            addCriterion("va_hpys_name not like", value, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameIn(List<String> values) {
            addCriterion("va_hpys_name in", values, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameNotIn(List<String> values) {
            addCriterion("va_hpys_name not in", values, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameBetween(String value1, String value2) {
            addCriterion("va_hpys_name between", value1, value2, "vaHpysName");
            return (Criteria) this;
        }

        public Criteria andVaHpysNameNotBetween(String value1, String value2) {
            addCriterion("va_hpys_name not between", value1, value2, "vaHpysName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_hpys
     *
     * @mbg.generated do_not_delete_during_merge Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}