package com.zhuanjingkj.stpbe.platform.domain;

public class VaHpgg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpgg.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer vaHpggId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpgg.va_hpgg_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaHpggName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpgg.va_hpgg_id
     *
     * @return the value of t_va_hpgg.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getVaHpggId() {
        return vaHpggId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpgg.va_hpgg_id
     *
     * @param vaHpggId the value for t_va_hpgg.va_hpgg_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpggId(Integer vaHpggId) {
        this.vaHpggId = vaHpggId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpgg.va_hpgg_name
     *
     * @return the value of t_va_hpgg.va_hpgg_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaHpggName() {
        return vaHpggName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpgg.va_hpgg_name
     *
     * @param vaHpggName the value for t_va_hpgg.va_hpgg_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpggName(String vaHpggName) {
        this.vaHpggName = vaHpggName == null ? null : vaHpggName.trim();
    }
}