package com.zhuanjingkj.stpbe.platform.domain;

public class VaHpys {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpys.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer vaHpysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpys.va_hpys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaHpysCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpys.va_hpys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaHpysName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpys.va_hpys_id
     *
     * @return the value of t_va_hpys.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getVaHpysId() {
        return vaHpysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpys.va_hpys_id
     *
     * @param vaHpysId the value for t_va_hpys.va_hpys_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpysId(Integer vaHpysId) {
        this.vaHpysId = vaHpysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpys.va_hpys_code
     *
     * @return the value of t_va_hpys.va_hpys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaHpysCode() {
        return vaHpysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpys.va_hpys_code
     *
     * @param vaHpysCode the value for t_va_hpys.va_hpys_code
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpysCode(String vaHpysCode) {
        this.vaHpysCode = vaHpysCode == null ? null : vaHpysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpys.va_hpys_name
     *
     * @return the value of t_va_hpys.va_hpys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaHpysName() {
        return vaHpysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpys.va_hpys_name
     *
     * @param vaHpysName the value for t_va_hpys.va_hpys_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpysName(String vaHpysName) {
        this.vaHpysName = vaHpysName == null ? null : vaHpysName.trim();
    }
}