package com.zhuanjingkj.stpbe.platform.domain;

public class VaHpzl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpzl.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private Integer vaHpzlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpzl.va_hpzl_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    private String vaHpzlName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpzl.va_hpzl_id
     *
     * @return the value of t_va_hpzl.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public Integer getVaHpzlId() {
        return vaHpzlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpzl.va_hpzl_id
     *
     * @param vaHpzlId the value for t_va_hpzl.va_hpzl_id
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpzlId(Integer vaHpzlId) {
        this.vaHpzlId = vaHpzlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpzl.va_hpzl_name
     *
     * @return the value of t_va_hpzl.va_hpzl_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public String getVaHpzlName() {
        return vaHpzlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpzl.va_hpzl_name
     *
     * @param vaHpzlName the value for t_va_hpzl.va_hpzl_name
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    public void setVaHpzlName(String vaHpzlName) {
        this.vaHpzlName = vaHpzlName == null ? null : vaHpzlName.trim();
    }
}