package com.zhuanjingkj.stpbe.tradataplat.domain;

public class ImgVaCxtz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Long imgVaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.cxtz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String cxtzJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer vaCllxflId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Byte vaCllxzflId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_csys_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer vaCsysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_clpp_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Long vaClppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_ppcx_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Long vaPpcxId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.va_cxnk_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Long vaCxnkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_cxtz.ppxhkxd
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer ppxhkxd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.img_va_id
     *
     * @return the value of t_img_va_cxtz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Long getImgVaId() {
        return imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.img_va_id
     *
     * @param imgVaId the value for t_img_va_cxtz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setImgVaId(Long imgVaId) {
        this.imgVaId = imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.cxtz_json
     *
     * @return the value of t_img_va_cxtz.cxtz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getCxtzJson() {
        return cxtzJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.cxtz_json
     *
     * @param cxtzJson the value for t_img_va_cxtz.cxtz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setCxtzJson(String cxtzJson) {
        this.cxtzJson = cxtzJson == null ? null : cxtzJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_cllxfl_id
     *
     * @return the value of t_img_va_cxtz.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getVaCllxflId() {
        return vaCllxflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_cllxfl_id
     *
     * @param vaCllxflId the value for t_img_va_cxtz.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxflId(Integer vaCllxflId) {
        this.vaCllxflId = vaCllxflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_cllxzfl_id
     *
     * @return the value of t_img_va_cxtz.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Byte getVaCllxzflId() {
        return vaCllxzflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_cllxzfl_id
     *
     * @param vaCllxzflId the value for t_img_va_cxtz.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxzflId(Byte vaCllxzflId) {
        this.vaCllxzflId = vaCllxzflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_csys_id
     *
     * @return the value of t_img_va_cxtz.va_csys_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getVaCsysId() {
        return vaCsysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_csys_id
     *
     * @param vaCsysId the value for t_img_va_cxtz.va_csys_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCsysId(Integer vaCsysId) {
        this.vaCsysId = vaCsysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_clpp_id
     *
     * @return the value of t_img_va_cxtz.va_clpp_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Long getVaClppId() {
        return vaClppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_clpp_id
     *
     * @param vaClppId the value for t_img_va_cxtz.va_clpp_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaClppId(Long vaClppId) {
        this.vaClppId = vaClppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_ppcx_id
     *
     * @return the value of t_img_va_cxtz.va_ppcx_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Long getVaPpcxId() {
        return vaPpcxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_ppcx_id
     *
     * @param vaPpcxId the value for t_img_va_cxtz.va_ppcx_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaPpcxId(Long vaPpcxId) {
        this.vaPpcxId = vaPpcxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.va_cxnk_id
     *
     * @return the value of t_img_va_cxtz.va_cxnk_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Long getVaCxnkId() {
        return vaCxnkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.va_cxnk_id
     *
     * @param vaCxnkId the value for t_img_va_cxtz.va_cxnk_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCxnkId(Long vaCxnkId) {
        this.vaCxnkId = vaCxnkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_cxtz.ppxhkxd
     *
     * @return the value of t_img_va_cxtz.ppxhkxd
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getPpxhkxd() {
        return ppxhkxd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_cxtz.ppxhkxd
     *
     * @param ppxhkxd the value for t_img_va_cxtz.ppxhkxd
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setPpxhkxd(Integer ppxhkxd) {
        this.ppxhkxd = ppxhkxd;
    }
}