package com.zhuanjingkj.stpbe.tradataplat.domain;

public class ImgVaWztz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Long imgVaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.wztz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String wztzJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.clwz_x
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer clwzX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.clwz_y
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer clwzY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.clwz_w
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer clwzW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.clwz_h
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer clwzH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_va_wztz.psfx
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Byte psfx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.img_va_id
     *
     * @return the value of t_img_va_wztz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Long getImgVaId() {
        return imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.img_va_id
     *
     * @param imgVaId the value for t_img_va_wztz.img_va_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setImgVaId(Long imgVaId) {
        this.imgVaId = imgVaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.wztz_json
     *
     * @return the value of t_img_va_wztz.wztz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getWztzJson() {
        return wztzJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.wztz_json
     *
     * @param wztzJson the value for t_img_va_wztz.wztz_json
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setWztzJson(String wztzJson) {
        this.wztzJson = wztzJson == null ? null : wztzJson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.clwz_x
     *
     * @return the value of t_img_va_wztz.clwz_x
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getClwzX() {
        return clwzX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.clwz_x
     *
     * @param clwzX the value for t_img_va_wztz.clwz_x
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setClwzX(Integer clwzX) {
        this.clwzX = clwzX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.clwz_y
     *
     * @return the value of t_img_va_wztz.clwz_y
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getClwzY() {
        return clwzY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.clwz_y
     *
     * @param clwzY the value for t_img_va_wztz.clwz_y
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setClwzY(Integer clwzY) {
        this.clwzY = clwzY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.clwz_w
     *
     * @return the value of t_img_va_wztz.clwz_w
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getClwzW() {
        return clwzW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.clwz_w
     *
     * @param clwzW the value for t_img_va_wztz.clwz_w
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setClwzW(Integer clwzW) {
        this.clwzW = clwzW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.clwz_h
     *
     * @return the value of t_img_va_wztz.clwz_h
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getClwzH() {
        return clwzH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.clwz_h
     *
     * @param clwzH the value for t_img_va_wztz.clwz_h
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setClwzH(Integer clwzH) {
        this.clwzH = clwzH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_va_wztz.psfx
     *
     * @return the value of t_img_va_wztz.psfx
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Byte getPsfx() {
        return psfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_va_wztz.psfx
     *
     * @param psfx the value for t_img_va_wztz.psfx
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setPsfx(Byte psfx) {
        this.psfx = psfx;
    }
}