package com.zhuanjingkj.stpbe.tradataplat.domain;

public class VaCllxfl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxfl.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer vaCllxflId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxfl.va_cllxfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String vaCllxflCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxfl.va_cllxfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String vaCllxflName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxfl.va_cllxfl_id
     *
     * @return the value of t_va_cllxfl.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getVaCllxflId() {
        return vaCllxflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxfl.va_cllxfl_id
     *
     * @param vaCllxflId the value for t_va_cllxfl.va_cllxfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxflId(Integer vaCllxflId) {
        this.vaCllxflId = vaCllxflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxfl.va_cllxfl_code
     *
     * @return the value of t_va_cllxfl.va_cllxfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getVaCllxflCode() {
        return vaCllxflCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxfl.va_cllxfl_code
     *
     * @param vaCllxflCode the value for t_va_cllxfl.va_cllxfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxflCode(String vaCllxflCode) {
        this.vaCllxflCode = vaCllxflCode == null ? null : vaCllxflCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxfl.va_cllxfl_name
     *
     * @return the value of t_va_cllxfl.va_cllxfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getVaCllxflName() {
        return vaCllxflName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxfl.va_cllxfl_name
     *
     * @param vaCllxflName the value for t_va_cllxfl.va_cllxfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxflName(String vaCllxflName) {
        this.vaCllxflName = vaCllxflName == null ? null : vaCllxflName.trim();
    }
}