package com.zhuanjingkj.stpbe.tradataplat.domain;

public class VaCllxzfl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxzfl.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Byte vaCllxzflId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxzfl.va_cllxzfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String vaCllxzflCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_cllxzfl.va_cllxzfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String vaCllxzflName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxzfl.va_cllxzfl_id
     *
     * @return the value of t_va_cllxzfl.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Byte getVaCllxzflId() {
        return vaCllxzflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxzfl.va_cllxzfl_id
     *
     * @param vaCllxzflId the value for t_va_cllxzfl.va_cllxzfl_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxzflId(Byte vaCllxzflId) {
        this.vaCllxzflId = vaCllxzflId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxzfl.va_cllxzfl_code
     *
     * @return the value of t_va_cllxzfl.va_cllxzfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getVaCllxzflCode() {
        return vaCllxzflCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxzfl.va_cllxzfl_code
     *
     * @param vaCllxzflCode the value for t_va_cllxzfl.va_cllxzfl_code
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxzflCode(String vaCllxzflCode) {
        this.vaCllxzflCode = vaCllxzflCode == null ? null : vaCllxzflCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_cllxzfl.va_cllxzfl_name
     *
     * @return the value of t_va_cllxzfl.va_cllxzfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getVaCllxzflName() {
        return vaCllxzflName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_cllxzfl.va_cllxzfl_name
     *
     * @param vaCllxzflName the value for t_va_cllxzfl.va_cllxzfl_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaCllxzflName(String vaCllxzflName) {
        this.vaCllxzflName = vaCllxzflName == null ? null : vaCllxzflName.trim();
    }
}