package com.zhuanjingkj.stpbe.tradataplat.domain;

public class VaHpzt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpzt.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private Integer vaHpztId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_va_hpzt.va_hpzt_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    private String vaHpztName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpzt.va_hpzt_id
     *
     * @return the value of t_va_hpzt.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public Integer getVaHpztId() {
        return vaHpztId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpzt.va_hpzt_id
     *
     * @param vaHpztId the value for t_va_hpzt.va_hpzt_id
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaHpztId(Integer vaHpztId) {
        this.vaHpztId = vaHpztId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_va_hpzt.va_hpzt_name
     *
     * @return the value of t_va_hpzt.va_hpzt_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public String getVaHpztName() {
        return vaHpztName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_va_hpzt.va_hpzt_name
     *
     * @param vaHpztName the value for t_va_hpzt.va_hpzt_name
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    public void setVaHpztName(String vaHpztName) {
        this.vaHpztName = vaHpztName == null ? null : vaHpztName.trim();
    }
}