package com.zhuanjingkj.stpbe.tradataplat.dao;

import com.zhuanjingkj.stpbe.tradataplat.domain.Image;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    long countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    Image selectByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKey(Image record);
}