package com.zhuanjingkj.stpbe.tradataplat.dao;

import com.zhuanjingkj.stpbe.tradataplat.domain.ImgVaWztz;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface ImgVaWztzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    long countByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByPrimaryKey(Long imgVaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insert(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insertSelective(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    List<ImgVaWztz> selectByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    ImgVaWztz selectByPrimaryKey(Long imgVaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImgVaWztz record, @Param("example") ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExample(@Param("record") ImgVaWztz record, @Param("example") ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKeySelective(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKey(ImgVaWztz record);
}