package com.zhuanjingkj.stpbe.tradataplat.dao;

import com.zhuanjingkj.stpbe.tradataplat.domain.VaHpzl;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface VaHpzlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    long countByExample(VaHpzlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByExample(VaHpzlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByPrimaryKey(Integer vaHpzlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insert(VaHpzl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insertSelective(VaHpzl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    List<VaHpzl> selectByExample(VaHpzlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    VaHpzl selectByPrimaryKey(Integer vaHpzlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaHpzl record, @Param("example") VaHpzlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExample(@Param("record") VaHpzl record, @Param("example") VaHpzlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKeySelective(VaHpzl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzl
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKey(VaHpzl record);
}