package com.zhuanjingkj.stpbe.tradataplat.dao;

import com.zhuanjingkj.stpbe.tradataplat.domain.VaHpgg;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;


@Mapper
public interface VaHpggMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    long countByExample(VaHpggExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByExample(VaHpggExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int deleteByPrimaryKey(Integer vaHpggId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insert(VaHpgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int insertSelective(VaHpgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    List<VaHpgg> selectByExample(VaHpggExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    VaHpgg selectByPrimaryKey(Integer vaHpggId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaHpgg record, @Param("example") VaHpggExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByExample(@Param("record") VaHpgg record, @Param("example") VaHpggExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKeySelective(VaHpgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpgg
     *
     * @mbg.generated Tue Nov 17 12:09:26 CST 2020
     */
    int updateByPrimaryKey(VaHpgg record);
}