package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.Camera;
import com.zhuanjingkj.stpbe.platform.domain.CameraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CameraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    long countByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByPrimaryKey(Long cameraId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insert(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insertSelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    List<Camera> selectByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    Camera selectByPrimaryKey(Long cameraId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Camera record, @Param("example") CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExample(@Param("record") Camera record, @Param("example") CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKeySelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKey(Camera record);
}