package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.CameraType;
import com.zhuanjingkj.stpbe.platform.domain.CameraTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CameraTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    long countByExample(CameraTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByExample(CameraTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByPrimaryKey(Integer cameraTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insert(CameraType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insertSelective(CameraType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    List<CameraType> selectByExample(CameraTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    CameraType selectByPrimaryKey(Integer cameraTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") CameraType record, @Param("example") CameraTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExample(@Param("record") CameraType record, @Param("example") CameraTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKeySelective(CameraType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera_type
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKey(CameraType record);
}