package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.Image;
import com.zhuanjingkj.stpbe.platform.domain.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    long countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int deleteByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    Image selectByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image
     *
     * @mbg.generated Tue Nov 17 19:02:07 CST 2020
     */
    int updateByPrimaryKey(Image record);
}