package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.ImgType;
import com.zhuanjingkj.stpbe.platform.domain.ImgTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(ImgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(ImgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Integer imgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(ImgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(ImgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<ImgType> selectByExample(ImgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    ImgType selectByPrimaryKey(Integer imgTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImgType record, @Param("example") ImgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") ImgType record, @Param("example") ImgTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(ImgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_type
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(ImgType record);
}