package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.ImgVaWztz;
import com.zhuanjingkj.stpbe.platform.domain.ImgVaWztzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgVaWztzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Long imgVaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<ImgVaWztz> selectByExample(ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    ImgVaWztz selectByPrimaryKey(Long imgVaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") ImgVaWztz record, @Param("example") ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") ImgVaWztz record, @Param("example") ImgVaWztzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(ImgVaWztz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_va_wztz
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(ImgVaWztz record);
}