package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.VaCllxfl;
import com.zhuanjingkj.stpbe.platform.domain.VaCllxflExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaCllxflMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(VaCllxflExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(VaCllxflExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Integer vaCllxflId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(VaCllxfl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(VaCllxfl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<VaCllxfl> selectByExample(VaCllxflExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    VaCllxfl selectByPrimaryKey(Integer vaCllxflId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaCllxfl record, @Param("example") VaCllxflExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") VaCllxfl record, @Param("example") VaCllxflExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(VaCllxfl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_cllxfl
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(VaCllxfl record);
}