package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.VaCsys;
import com.zhuanjingkj.stpbe.platform.domain.VaCsysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaCsysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(VaCsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(VaCsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Integer vaCsysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(VaCsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(VaCsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<VaCsys> selectByExample(VaCsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    VaCsys selectByPrimaryKey(Integer vaCsysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaCsys record, @Param("example") VaCsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") VaCsys record, @Param("example") VaCsysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(VaCsys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_csys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(VaCsys record);
}