package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.VaHpys;
import com.zhuanjingkj.stpbe.platform.domain.VaHpysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaHpysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(VaHpysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(VaHpysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Integer vaHpysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(VaHpys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(VaHpys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<VaHpys> selectByExample(VaHpysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    VaHpys selectByPrimaryKey(Integer vaHpysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaHpys record, @Param("example") VaHpysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") VaHpys record, @Param("example") VaHpysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(VaHpys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpys
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(VaHpys record);
}