package com.zhuanjingkj.stpbe.platform.mapper;

import com.zhuanjingkj.stpbe.platform.domain.VaHpzt;
import com.zhuanjingkj.stpbe.platform.domain.VaHpztExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VaHpztMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    long countByExample(VaHpztExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByExample(VaHpztExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int deleteByPrimaryKey(Integer vaHpztId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insert(VaHpzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int insertSelective(VaHpzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    List<VaHpzt> selectByExample(VaHpztExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    VaHpzt selectByPrimaryKey(Integer vaHpztId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") VaHpzt record, @Param("example") VaHpztExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByExample(@Param("record") VaHpzt record, @Param("example") VaHpztExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKeySelective(VaHpzt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_va_hpzt
     *
     * @mbg.generated Tue Nov 17 19:02:08 CST 2020
     */
    int updateByPrimaryKey(VaHpzt record);
}